apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "threads-tracker.fullname" . }}-migrations
  labels:
    {{- include "threads-tracker.labels" . | nindent 4 }}
    app.kubernetes.io/component: migrations
  annotations:
    "helm.sh/hook": pre-upgrade, pre-install
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      labels:
        {{- include "threads-tracker.labels" . | nindent 8 }}
        app.kubernetes.io/component: migrations
    spec:
      restartPolicy: Never
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.migrations.podSecurityContext | nindent 8 }}
      containers:
        - name: migrations
          securityContext:
            {{- toYaml .Values.migrations.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/sh
            - -c
            - bin/console doctrine:migrations:migrate
          env:
            {{- include "threads-tracker.env" . | nindent 12 }}
          {{- with  .Values.migrations.resources}}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.migrations.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.migrations.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
