framework:
    messenger:
        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            mastodon: '%env(MESSENGER_TRANSPORT_DSN)%/mastodon'
            threads_check: '%env(MESSENGER_TRANSPORT_DSN)%/threads_check'
            failed: 'doctrine://default?queue_name=failed'

        routing:
            App\Message\FetchMastodonNotificationsMessage: mastodon
            App\Message\ProcessMastodonNotificationMessage: mastodon
            App\Message\PostMastodonPrivateMentionMessage: mastodon
            App\Message\SendUserFederatedNotificationsMessage: mastodon

            App\Message\StartBatchCheckingMessage: threads_check
            App\Message\CheckThreadUserMessage: threads_check


# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
