# hear me out : a post on threads is called a zucc and I won't accept anything else
# have you seen my last re-zucc ?
# have you seen what @firefox just zucced ?

services:
  php:
    build:
      context: .
      target: app_php_dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    restart: unless-stopped
    ports:
      # HTTP
      - target: 80
        published: ${HTTP_PORT:-80}
        protocol: tcp
      # HTTPS
      - target: 443
        published: ${HTTPS_PORT:-443}
        protocol: tcp
      # HTTP/3
      - target: 443
        published: ${HTTP3_PORT:-443}
        protocol: udp
    volumes:
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      - ./docker/frankenphp/Caddyfile:/etc/caddy/Caddyfile:ro
      - ./:/srv/app
    tmpfs:
      - /data:mode=770,uid=${UID:-1000},gid=${GID:-1000}
      - /config:mode=770,uid=${UID:-1000},gid=${GID:-1000}
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      SERVER_NAME: ${SERVER_NAME:-localhost, php:80, :9153}
      XDEBUG_MODE: ${XDEBUG_MODE:-off}
      DATABASE_HOST: 'database'
      DATABASE_PORT: '5432'
      DATABASE_USER: ${POSTGRES_USER:-app}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      DATABASE_NAME: ${POSTGRES_DB:-app}
      DATABASE_VERSION: ${POSTGRES_VERSION:-16}
      MESSENGER_TRANSPORT_DSN: 'redis://redis:6379'
      LOCK_DSN: 'redis://redis:6379'
      LOG_LEVEL: ${LOG_LEVEL:-info}
  
  # Mercure is installed as a Caddy module, prevent the Flex recipe from installing another service
  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###
  
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
###< doctrine/doctrine-bundle ###

  redis:
    image: redis:7.0-alpine
    ports:
      - "6379:6379"

volumes:
  php_socket:
  caddy_data:
  caddy_config:
  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###
  
  ###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
