x-base: &base
  image: ghcr.io/rivals-space/threads-stalker:${APP_VERSION:-latest}
  tmpfs:
    - /data:mode=770,uid=${UID:-1000},gid=${GID:-1000}
    - /config:mode=770,uid=${UID:-1000},gid=${GID:-1000}
  depends_on:
    - database
  env_file:
    - .env.prod.local
  environment:
    SERVER_NAME: ${SERVER_NAME:-localhost, php:80, :9153}
    DATABASE_HOST: 'database'
    DATABASE_PORT: '5432'
    DATABASE_USER: ${POSTGRES_USER:-app}
    DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
    DATABASE_NAME: ${POSTGRES_DB:-app}
    DATABASE_VERSION: ${POSTGRES_VERSION:-16}
    MESSENGER_TRANSPORT_DSN: redis://redis:6379
    LOG_LEVEL: ${LOG_LEVEL:-info}

services:
  app-setup:
    <<: *base
    command: "bin/console doctrine:migrations:migrate"
    depends_on:
      database:
        condition: service_healthy

  app-scheduler:
    <<: *base
    command: "bin/console messenger:consume scheduler_default -v"
    depends_on:
      database:
        condition: service_healthy
      app-setup:
        condition: service_completed_successfully

  app-messenger-mastodon:
    <<: *base
    command: "bin/console messenger:consume mastodon -v"
    depends_on:
      database:
        condition: service_healthy
      app-setup:
        condition: service_completed_successfully

  app-messenger-threads-check:
    <<: *base
    command: "bin/console messenger:consume threads_check -v"
    depends_on:
      database:
        condition: service_healthy
      app-setup:
        condition: service_completed_successfully

  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - database_data:/var/lib/postgresql/data:rw

  redis:
    image: redis:7.0-alpine

volumes:
  database_data: