name: "Releaser"

on:
  push:
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write

jobs: 
  releaser:
    runs-on: ubuntu-latest
    steps:

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          command: manifest
          token: '${{ secrets.BOT_PAT }}'